services:
  spark-master:
    image: bitnami/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_CLASSPATH=/opt/bitnami/spark/libs/*
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./jobs/spark/conf:/opt/bitnami/spark/conf
      - ./jobs/spark/libs:/opt/bitnami/spark/libs
      - ./jobs/python:/opt/bitnami/spark/apps
    networks:
      - mercury-network

  spark-worker:
    image: bitnami/spark:3.5.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jobs/spark/conf:/opt/bitnami/spark/conf
      - ./jobs/spark/libs:/opt/bitnami/spark/libs
    depends_on:
      - spark-master
    networks:
      - mercury-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - mercury-network

networks:
  mercury-network:
    driver: bridge
