version: 2

models:
  - name: stg_installs
    description: Unified and cleaned installs data from AppsFlyer
    columns:
      - name: event_time
        description: Timestamp of the install
        tests:
          - not_null
      - name: event_name
        description: Name of the event (install)
      - name: media_source
        description: Source of the campaign
      - name: campaign
        description: Campaign name
      - name: platform
        description: Platform (ios or android)
      - name: app_id
        description: Application ID (id123456789 or com.appsflyer.referrersender)
        tests:
          - accepted_values:
              values: ['id123456789', 'com.appsflyer.referrersender']
      - name: user_id
        description: Unique user identifier
      - name: cost
        description: Cost associated with the install
      - name: revenue
        description: Revenue (0 for installs)

  - name: stg_in_app_events
    description: Unified and cleaned in-app events data from AppsFlyer
    columns:
      - name: event_time
        description: Timestamp of the event
        tests:
          - not_null
      - name: event_name
        description: Name of the event (af_purchase)
      - name: media_source
        description: Source of the campaign
      - name: campaign
        description: Campaign name
      - name: platform
        description: Platform (ios or android)
      - name: app_id
        description: Application ID (id123456789 or com.appsflyer.referrersender)
        tests:
          - accepted_values:
              values: ['id123456789', 'com.appsflyer.referrersender']
      - name: user_id
        description: Unique user identifier
      - name: cost
        description: Cost (0 for in-app events)
      - name: revenue
        description: Revenue from the event

  - name: stg_events
    description: Standardized dataset combining installs and in-app events
    columns:
      - name: event_time
        description: Timestamp of the event
        tests:
          - not_null
      - name: event_name
        description: Name of the event (install or af_purchase)
        tests:
          - accepted_values:
              values: ['install', 'af_purchase']
      - name: media_source
        description: Source of the campaign
      - name: campaign
        description: Campaign name
      - name: platform
        description: Platform (ios or android)
      - name: app_id
        description: Application ID (id123456789 or com.appsflyer.referrersender)
        tests:
          - accepted_values:
              values: ['id123456789', 'com.appsflyer.referrersender']
      - name: user_id
        description: Unique user identifier
      - name: cost
        description: Cost associated with the event
      - name: revenue
        description: Revenue associated with the event

  - name: campaign_performance
    description: Aggregated campaign performance metrics
    columns:
      - name: media_source
        description: Source of the campaign
      - name: campaign
        description: Campaign name
      - name: app_id
        description: Application ID (id123456789 or com.appsflyer.referrersender)
        tests:
          - accepted_values:
              values: ['id123456789', 'com.appsflyer.referrersender']
      - name: platform
        description: Platform (ios or android)
      - name: event_date
        description: Date of the event
        tests:
          - not_null
      - name: install_count
        description: Number of installs
      - name: total_cost
        description: Total campaign spend
      - name: total_revenue
        description: Total revenue from purchases within 7 days
      - name: cpi
        description: Cost per install
      - name: roas_7d
        description: 7-day return on ad spend (percentage)