version: 2

sources:
  - name: appsflyer_raw
    database: smart_view
    schema: raw
    tables:
      - name: installs
        description: Combined installs reports (organic and non-organic) for iOS and Android
        meta:
          spark:
            format: csv
            options:
              header: true
              inferSchema: true
        external:
          location: 's3a://mercury/smart_view/raw/{id123456789,com.appsflyer.referrersender}/{installs_report,organic_installs_report}/*'
      - name: in_app_events
        description: Combined in-app events reports (organic and non-organic) for iOS and Android
        meta:
          spark:
            format: csv
            options:
              header: true
              inferSchema: true
        external:
          location: 's3a://mercury/smart_view/raw/{id123456789,com.appsflyer.referrersender}/{in_app_events_report,organic_in_app_events_report}/*'