default:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_HOST', 'spark-master') }}"
      port: "{{ env_var('SPARK_PORT', '7077') }}"
      schema: marts
      database: smart_view
      user: "{{ env_var('SPARK_USER', 'admin') }}"
      password: "{{ env_var('SPARK_PASSWORD', '') }}"
      threads: 4
      file_format: parquet